# Generated by Django 2.1.7 on 2019-02-14 03:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('description', models.CharField(max_length=3000, null=True)),
                ('status', models.CharField(choices=[('recruiting', 'Набор участников'), ('in_progress', 'В процессе'), ('finished', 'Окончен'), ('paused', 'Приостановлен'), ('on_hold', 'Заморожен')], max_length=20)),
                ('estimated_start_date', models.DateTimeField()),
                ('estimated_finish_date', models.DateTimeField()),
                ('is_published', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in', 'Участник проекта'), ('invited', 'Приглашен в проект'), ('entry_request', 'Отправлен запрос на вступление в команду'), ('invite_rejected', 'Приглашение отклонено'), ('entry_request_rejected', 'Запрос на вступление отклонен'), ('self_leaved', 'Уход из проекта по собственной инициативе'), ('dismissed', 'Уход из проекта по инициативе менеджера проекта')], max_length=100)),
                ('role', models.CharField(choices=[('owner', 'Создатель проекта'), ('manager', 'Менеджер'), ('employee', 'Участник')], max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=3000, null=True)),
                ('salary', models.CharField(default='По договоренности', max_length=255)),
                ('is_archived', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Project')),
            ],
        ),
        migrations.CreateModel(
            name='VacancyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WallPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=5000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainsite.Project')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='login_method',
            field=models.CharField(choices=[('g', 'Login with Google'), ('e', 'Login with Email'), ('vk', 'Login with VK')], max_length=2),
        ),
        migrations.AddField(
            model_name='wallpost',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='vacancy_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.VacancyType'),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='vacancy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mainsite.Vacancy'),
        ),
    ]
