# Generated by Django 2.1.7 on 2019-02-14 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_auto_20190214_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=3000, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='project',
            name='estimated_finish_date',
            field=models.DateTimeField(verbose_name='Дата окончания проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='estimated_start_date',
            field=models.DateTimeField(verbose_name='Дата начала проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_published',
            field=models.BooleanField(verbose_name='Проект доступен в поиске'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=512, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('recruiting', 'Набор участников'), ('in_progress', 'В процессе'), ('finished', 'Окончен'), ('paused', 'Приостановлен'), ('on_hold', 'Заморожен')], max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='role',
            field=models.CharField(choices=[('owner', 'Создатель проекта'), ('manager', 'Менеджер'), ('employee', 'Участник')], max_length=20, verbose_name='Роль в проекте'),
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='status',
            field=models.CharField(choices=[('in', 'Участник проекта'), ('invited', 'Приглашен в проект'), ('entry_request', 'Отправлен запрос на вступление в команду'), ('invite_rejected', 'Приглашение отклонено'), ('entry_request_rejected', 'Запрос на вступление отклонен'), ('self_leaved', 'Уход из проекта по собственной инициативе'), ('dismissed', 'Уход из проекта по инициативе менеджера проекта')], max_length=100, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(null=True, verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.CharField(max_length=3000, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Скрыть вакансию'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.CharField(default='По договоренности', max_length=255, verbose_name='Вознаграждение'),
        ),
    ]
